package org.example.jobservice.enums;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,
    APPLICATION_WITHDRAWN,
    AWAITING_VALIDATION,
    MISSION_VALIDATED,
    REVIEW_RECEIVED,
    MISSION_COMPLETED
}
