server:
  port: 8083

spring:
  application:
    name: job-service

  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/freelance_job_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

# URL de auth-service pour valider le JWT
auth-service:
  url: http://localhost:8081

# URL de user-service pour les appels Feign wallet/profile
user-service:
  url: http://localhost:8082

# JWT (meme secret que auth-service !)
app:
  jwt:
    secret: "${JWT_SECRET}"
  internal:
    secret: ${INTERNAL_API_SECRET:dev-internal-secret-change-me}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.example.jobservice.security: DEBUG

